In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
from datetime import datetime

data_dir = Path('../data')

In [2]:
csv = data_dir/f'ImageJcsvs/C2_20221219_control_1.csv'

In [3]:
dataframe_from_file = pd.read_csv(csv, header=0)

In [4]:
dataframe_from_file

,Label,ID,TRACK_ID,QUALITY,POSITION_X,POSITION_Y,POSITION_Z,POSITION_T,FRAME,RADIUS,...,MANUAL_COLOR,MEAN_INTENSITY,MEDIAN_INTENSITY,MIN_INTENSITY,MAX_INTENSITY,TOTAL_INTENSITY,STANDARD_DEVIATION,ESTIMATED_DIAMETER,CONTRAST,SNR
0,ID70524,70524,0,2.403,556.730,289.341,0,0,0,7.5,...,-10921639,26.847,15,3,255,4752,42.284,4.066,0.340,0.322
1,ID71086,71086,0,2.661,556.443,288.783,0,30,1,7.5,...,-10921639,26.768,13,2,255,4738,47.356,4.030,0.365,0.302
2,ID71937,71937,0,2.540,555.806,289.427,0,60,2,7.5,...,-10921639,26.407,13,1,255,4674,44.628,3.955,0.334,0.296
3,ID70668,70668,0,2.614,555.499,290.004,0,90,3,7.5,...,-10921639,26.616,13,2,255,4711,45.449,3.000,0.337,0.295
4,ID71657,71657,0,2.395,556.023,290.422,0,120,4,7.5,...,-10921639,25.209,13,2,255,4462,42.973,4.258,0.312,0.279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49892,ID121086,121086,1679,2.445,19.197,229.572,0,10770,359,7.5,...,-10921639,30.034,15,5,175,5316,35.985,7.003,0.395,0.473
49893,ID120972,120972,1680,2.565,451.345,260.468,0,10740,358,7.5,...,-10921639,27.684,13,4,255,4900,46.069,28.500,0.207,0.206
49894,ID121096,121096,1680,2.520,451.464,259.970,0,10770,359,7.5,...,-10921639,28.164,14,2,255,4985,43.648,28.500,0.223,0.235
49895,ID121009,121009,1681,2.195,408.380,430.581,0,10740,358,7.5,...,-10921639,55.407,45,14,255,9807,40.925,22.334,0.083,0.206
49896,ID121135,121135,1681,2.258,406.155,427.033,0,10770,359,7.5,...,-10921639,56.723,47,17,255,10040,39.404,3.000,0.100,0.262

In [6]:
def reformat_file(dataframe, xw, yw, loc):
    """
    reformat_file takes in the new dataframe created from the csv and the x-y wound location and reshapes the dataframe
    to clean up the column labels and add a new column called 'r' which holds the radial distance from the wound.
    Parameters (add types)
    ----------
    dataframe
    loc
    yw
    xw

    dataframe: dataframe converted from csv
    xw = x location of wound
    yw = y location of wound
    loc = location of file in folder (i.e. file 1 is A, file 2 is B, etc.), allows for multiple files to be concatenated
    Returns
    -------
    reshaped_dataframe: reshaped dataframe which has the correct column labels and radial_location parameters
    """

    reshaped_dataframe = pd.DataFrame(
        {'trackID': dataframe['TRACK_ID'], 't': dataframe['POSITION_T'], 'x': dataframe['POSITION_X'],
         'y': dataframe['POSITION_Y']})
    reshaped_dataframe['x'] = reshaped_dataframe['x'] - xw
    reshaped_dataframe['y'] = reshaped_dataframe['y'] - yw
    reshaped_dataframe['r'] = (lambda x, y: np.sqrt(x ** 2 + y ** 2))(reshaped_dataframe['x'], reshaped_dataframe['y'])
    reshaped_dataframe['trackID'] = reshaped_dataframe['trackID'].astype(str)
    #reshaped_dataframe.trackID = reshaped_dataframe.trackID + f"{loc}"  # creates a label for the tracks to be organised by, only needed if there are multiple files to run on

    return reshaped_dataframe

In [7]:
xw = 167
yw = (512 - 160)

In [9]:
df = reformat_file(dataframe_from_file,xw,yw,loc=0)

In [10]:
df

      trackID      t        x        y           r
0           0      0  389.730  -62.659  394.734877
1           0     30  389.443  -63.217  394.540542
2           0     60  388.806  -62.573  393.808946
3           0     90  388.499  -61.996  393.414510
4           0    120  389.023  -61.578  393.866405
...       ...    ...      ...      ...         ...
49892    1679  10770 -147.803 -122.428  191.922750
49893    1680  10740  284.345  -91.532  298.714221
49894    1680  10770  284.464  -92.030  298.980414
49895    1681  10740  241.380   78.581  253.848927
49896    1681  10770  239.155   75.033  250.649287

[49897 rows x 5 columns]

In [12]:
date = datetime.now().strftime("%Y_%m_%d-%I:%M:%S_%p")

date

'2023_01_26-10:55:37_AM'

In [14]:
import pickle  # Left import pickle here to remind myself that the below statement outputs a pickled dataframe

with open(f"../data/Trajectory_dataframes/new_{date}_control", "wb") as fp:  # Pickling
    pickle.dump(df, fp)